#!/usr/bin/env bash
# bash run commands for OS X

alias ls='gls --group-directories-first --color=auto'

# up the user-system-wide resource limit
ulimit -n 1024

export TERM=xterm-256color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1

export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
export LC_CTYPE=en_US.utf-8
export LC_ALL=en_US.utf-8

if [ -f `brew --prefix`/etc/bash_completion ]; then
    source `brew --prefix`/etc/bash_completion
fi
